use super::*;

impl Runner {
    pub(super) fn cmd_assert(&mut self, expr_str: &str) -> Result<(), CliError> {
        let val = self.eval(expr_str)?;
        match val {
            Value::Bool(true) => Ok(()),
            Value::Bool(false) => Err(CliError::Message(format!(
                "assertion failed: {} evaluated to false",
                expr_str
            ))),
            _ => Err(CliError::Message(format!(
                "assertion error: expected bool, got {}",
                value_type_display(&val)
            ))),
        }
    }

    pub(super) fn cmd_assert_eq(&mut self, tail: &str) -> Result<(), CliError> {
        let parts = split_top_level_commas(tail);
        if parts.len() != 2 {
            return Err(CliError::Message(
                "usage: assert_eq <expr1>, <expr2>".into(),
            ));
        }
        let left_str = parts[0].trim();
        let right_str = parts[1].trim();
        if left_str.is_empty() || right_str.is_empty() {
            return Err(CliError::Message(
                "usage: assert_eq <expr1>, <expr2>".into(),
            ));
        }
        let left = self.eval(left_str)?;
        let right = self.eval(right_str)?;
        if left == right {
            Ok(())
        } else {
            Err(CliError::Message(format!(
                "assertion failed: {} != {}\n  left:  {}\n  right: {}",
                left_str,
                right_str,
                format_value(&left, &self.unit_suffixes),
                format_value(&right, &self.unit_suffixes)
            )))
        }
    }

    pub(super) fn cmd_assert_err(&mut self, tail: &str) -> Result<(), CliError> {
        let output_len = self.output.len();
        match self.exec_inner(tail) {
            Err(_) => {
                // Expected error — suppress any output generated by the failed command
                self.output.truncate(output_len);
                Ok(())
            }
            Ok(()) => Err(CliError::Message(format!(
                "assertion failed: expected error from: {}",
                tail
            ))),
        }
    }
}
